[project]
name = "sarajevosmogsquad"
version = "0.1.0"
description = "Generate Sarajevo AQI graphics to raise awareness!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "pillow>=10.0.0",
    "requests>=2.32.5",
]
